# Generated by Django 2.0.13 on 2019-05-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rec',
            field=models.CharField(default='', max_length=30),
        ),
    ]
