# Generated by Django 2.0.13 on 2019-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='main_image',
            field=models.ImageField(default='image/unknown.png', upload_to='image/'),
        ),
    ]
