# Generated by Django 2.0.13 on 2019-05-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
